### ISSUE TITLE
Add www CNAME record

### ISSUE THREAD

**Issue by NunoAlexandre** [monadic-xyz/monadic.xyz#1]
Hi!

www.monadic.xyz is unreachable. I found this link provided on the [Monadic LinkedIn page](https://www.linkedin.com/company/monadic-gmbh/). The `www` CNAME record needs to be added.

**Comment by juliendonck** [comment]
@cloudhead you have access to the DNS stuff, right? You think you can take a look?

**Comment by juliendonck** [comment]
@NunoAlexandre this is what we have. What exactly is missing?

<img width="1118" alt="Screenshot 2020-03-04 at 10 12 36" src="https://user-images.githubusercontent.com/2326909/75863399-ae917280-5e00-11ea-986c-648236327099.png">

**Comment by juliendonck** [comment]
Also the namecheap credentials are in bitwarden if you want to take a look yourself.

**Comment by NunoAlexandre** [comment]
Fixed :heavy_check_mark:
